name: Test and Deploy

# run on push to master (includes when PR is merged) and test_deploy (testing of this script) or when manually triggered
on:
  push:
    branches: [ "master", "test-deploy"]
  workflow_dispatch:

jobs:
  test:
    # run tests first using reusable workflow test_caller, if tests fail, deploy job won't run
    uses: ./.github/workflows/test_caller.yml
    secrets:
      CONFIG: ${{ secrets.CONFIG }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

  deploy:
    needs: test
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    steps:
      # leave actual deployment empty for now