version: "3.9"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    depends_on:
      mongodb:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

  frontend:
    build:
      context: frontend-vecollab
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

  etherpad:
    build:
      context: https://github.com/ether/etherpad-lite.git
      dockerfile: Dockerfile
      args:
        - ETHERPAD_PLUGINS=ep_openid_connect
    environment:
      - TRUST_PROXY=true
      - EDIT_ONLY=true
      - REQUIRE_AUTHENTICATION=true
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt # unfortunately the api key cannot be supplied via config (why?!!!!!), so we have to inject it into the container to be able to use it in the rest of the application
      - ./etherpad_config.json:/opt/etherpad-lite/settings.json # because we use the openid connect plugin, which requires configuration in settings.json that is not achieveable via env variables, we have to inject a full etherpad configuration into the container
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:Z
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=CHANGEME
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

volumes:
  mongodb_data:
  elasticsearch:
