name: Test and Deploy

# run on push to staging (includes when PR is merged) and test_deploy (testing of this script) or when manually triggered
on:
  push:
    branches: [ "staging", "test_deploy"]
  workflow_dispatch:

jobs:
  backend_test:
    # run tests first using reusable workflow test_caller, if tests fail, deploy job won't run
    uses: ./.github/workflows/test_caller.yml
    secrets:
      BACKEND_ENV: ${{ secrets.BACKEND_ENV }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
  frontend_test:
    uses: ./.github/workflows/frontend_CI.yml
    secrets:
      FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  deploy:
    name: deploy to staging
    runs-on: ubuntu-latest
    needs: [backend_test,frontend_test]
    steps:
    - name: trigger deploy workflow webhook
      uses: distributhor/workflow-webhook@v3.0.5
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
