name: CI_frontend

on:
  workflow_call:
    secrets:
      FRONTEND_ENV:
        required: true
  workflow_dispatch:

jobs:
  analyze_code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-vecollab
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js (version extracted from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: './frontend-vecollab/.nvmrc'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/frontend-vecollab/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/frontend-vecollab/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .

      - name: Run TypeScript type checking
        run: npx tsc --noEmit

      - name: Create .env file
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > .env

      - name: Build React app
        run: npm run build

      - name: Generate Sitemap
        run: npm run sitemap

      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'http://127.0.0.1:3000'