name: CI
on: [push]
workflow_call:
  secrets:
    FRONTEND_ENV:
      required: true
    LHCI_GITHUB_APP_TOKEN:
      required: true
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-vecollab
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 20.10
        uses: actions/setup-node@v4
        with:
          node-version-file: './frontend-vecollab/.nvmrc'
      - name: Create .env file
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > .env
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}