name: Test

# run on push to any branches except master, staging or when manually triggered
# on push to master or staging the other deploy.yml workflows handles the test call itself
on:
  push:
    branches-ignore:
      - "master"
      - "staging"
  workflow_dispatch:

jobs:
  backend_test:
    uses: ./.github/workflows/test_caller.yml
    secrets:
      CONFIG: ${{ secrets.CONFIG }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
  frontend_test:
    uses: ./.github/workflows/frontend_CI.yml
    secrets:
      FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}