# this workflow has been separated to avoid copy pasting the same job, because on master tests and deploy is run and on the other branches only test runs
name: reusable test workflow

on:
  workflow_call: # workflow only runs when being called by another workflow
    secrets:
      MONGODB_USERNAME:
        required: true
      MONGODB_PASSWORD:
        required: true
      BACKEND_ENV:
        required: true

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo "${{ secrets.BACKEND_ENV }}" > .env
    - name: setup and start elasticsearch
      uses: getong/elasticsearch-action@v1.2
      with:
        elasticsearch version: '8.8.0'
        host port: 9200
        container port: 9200
        host node port: 9300
        node port: 9300
        discovery type: 'single-node'
    - name: setup and start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-username: ${{ secrets.MONGODB_USERNAME }}
        mongodb-password: ${{ secrets.MONGODB_PASSWORD }}
    - name: Run tests
      run: |
        python run_tests.py
    - name: Clean up config
      # even though runners get destroyed after execution: better safe than sorry, delete config file
      if: always()
      run: |
        rm -rf config.json