# this workflow has been separated to avoid copy pasting the same job, because on master tests and deploy is run and on the other branches only test runs
name: reusable test workflow

on:
  workflow_call: # workflow only runs when being called by another workflow
    secrets:
      CONFIG:
        required: true
      MONGODB_USERNAME:
        required: true
      MONGODB_PASSWORD:
        required: true

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up config from secrets
      # tests need config, but might contain sensitive data, workaround:
      # content of config.json has been base64 encoded in secrets (simple via base64 config.json)
      # now decode it and create the config file again
      run: |
        echo -n '${{ secrets.CONFIG }}' | base64 --decode > config.json
    - name: setup and start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-username: ${{ secrets.MONGODB_USERNAME }}
        mongodb-password: ${{ secrets.MONGODB_PASSWORD }}
    - name: Run tests
      run: |
        python -m tornado.testing tests/api_tests.py
    - name: Clean up config
      # even though runners get destroyed after execution: better safe than sorry, delete config file
      if: always()
      run: |
        rm -rf config.json